# Generated by Django 4.2.4 on 2023-08-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Club name')),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.category')),
            ],
        ),
    ]
