# Generated by Django 4.2.4 on 2023-08-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='Category',
            new_name='cat',
        ),
    ]
